// Sample dataset for demo mode (no backend configured). Shapes mirror the
// NestJS admin API responses exactly, so the pages don't know the difference.

const daysAgo = (n) => new Date(Date.now() - n * 86400000).toISOString();
const daysAhead = (n) => new Date(Date.now() + n * 86400000).toISOString();

const img = (id) => `https://images.unsplash.com/${id}?w=800&q=80`;

export function createDemoData() {
  const developers = [
    {
      id: "solaris",
      name: "SOLARIS DEVELOPMENTS",
      tagline: "Architecture for the next century",
      years_in_market: 22,
      total_projects: 48,
      international_hubs: "Dubai · London · Singapore",
      hero_image_url: img("photo-1486325212027-8081e485255e"),
      is_verified: true,
      is_approved: true,
      created_at: daysAgo(300),
      values: [
        { id: "sv1", icon: "trust", title: "Integrity", description: "Transparent reporting on every project.", display_order: 0 },
        { id: "sv2", icon: "quality", title: "Craftsmanship", description: "Award-winning architectural partners.", display_order: 1 },
      ],
    },
    {
      id: "berkeley",
      name: "BERKELEY GROUP",
      tagline: "London's landmark builder",
      years_in_market: 35,
      total_projects: 120,
      international_hubs: "London · Manchester",
      hero_image_url: img("photo-1464938050520-ef2270bb8ce8"),
      is_verified: true,
      is_approved: true,
      created_at: daysAgo(260),
      values: [
        { id: "bv1", icon: "global", title: "Heritage", description: "Three decades of delivery.", display_order: 0 },
      ],
    },
    {
      id: "meraas",
      name: "MERAAS HOLDING",
      tagline: "Shaping Dubai's waterfront",
      years_in_market: 17,
      total_projects: 36,
      international_hubs: "Dubai · Abu Dhabi",
      hero_image_url: img("photo-1512453979798-5ea266f8880c"),
      is_verified: true,
      is_approved: false,
      created_at: daysAgo(180),
      values: [],
    },
    {
      id: "aster",
      name: "ASTER CAPITAL ESTATES",
      tagline: "Boutique developments, institutional returns",
      years_in_market: 9,
      total_projects: 14,
      international_hubs: "New York · Miami",
      hero_image_url: img("photo-1449824913935-59a10b8d2000"),
      is_verified: false,
      is_approved: true,
      created_at: daysAgo(90),
      values: [],
    },
  ];

  const properties = [
    {
      id: "zenith",
      developer_id: "solaris",
      name: "The Zenith Residence",
      location: "Shoreditch, London",
      asset_class: "Multi-family",
      total_area: 87400,
      completion_date: daysAhead(420),
      min_entry_price: 25000,
      sustainability_rating: 4.0,
      overview:
        "The Zenith Residence redefines urban living in the heart of Shoreditch, blending contemporary architecture with community-centred design.",
      status: "active",
      created_at: daysAgo(200),
      media: [
        { id: "zm1", url: img("photo-1486325212027-8081e485255e"), type: "image", display_order: 0 },
        { id: "zm2", url: img("photo-1545324418-cc1a3fa10c00"), type: "image", display_order: 1 },
        { id: "zm3", url: img("photo-1560448204-e02f11c3d0e2"), type: "image", display_order: 2 },
      ],
      roi: { id: "zr", annual_return: 7.8, capital_appreciation: 5.2, rental_yield: 4.6, exit_horizon: "5 years" },
    },
    {
      id: "nexus",
      developer_id: "berkeley",
      name: "Nexus Plaza II",
      location: "London, Commercial District",
      asset_class: "Commercial",
      total_area: 145000,
      completion_date: daysAhead(540),
      min_entry_price: 35000,
      sustainability_rating: 4.0,
      overview: "A landmark commercial development anchoring the district's regeneration masterplan.",
      status: "active",
      created_at: daysAgo(160),
      media: [
        { id: "nm1", url: img("photo-1464938050520-ef2270bb8ce8"), type: "image", display_order: 0 },
        { id: "nm2", url: img("photo-1554435493-93422e8220c8"), type: "image", display_order: 1 },
      ],
      roi: { id: "nr", annual_return: 6.2, capital_appreciation: 4.8, rental_yield: 3.2, exit_horizon: "5–7 years" },
    },
    {
      id: "marina-gate",
      developer_id: "meraas",
      name: "Marina Gate Towers",
      location: "Dubai Marina, UAE",
      asset_class: "Residential",
      total_area: 210000,
      completion_date: daysAhead(720),
      min_entry_price: 50000,
      sustainability_rating: 4.5,
      overview: "Twin waterfront towers with panoramic marina views and hotel-grade amenities.",
      status: "coming_soon",
      created_at: daysAgo(120),
      media: [
        { id: "mm1", url: img("photo-1512453979798-5ea266f8880c"), type: "image", display_order: 0 },
      ],
      roi: { id: "mr", annual_return: 8.4, capital_appreciation: 6.1, rental_yield: 5.5, exit_horizon: "4 years" },
    },
    {
      id: "aster-park",
      developer_id: "aster",
      name: "Aster Park Lofts",
      location: "Brooklyn, New York",
      asset_class: "Mixed-use",
      total_area: 64000,
      completion_date: daysAgo(60),
      min_entry_price: 20000,
      sustainability_rating: 3.5,
      overview: "Converted industrial lofts with retail podium in a fast-appreciating neighbourhood.",
      status: "sold_out",
      created_at: daysAgo(340),
      media: [
        { id: "am1", url: img("photo-1449824913935-59a10b8d2000"), type: "image", display_order: 0 },
        { id: "am2", url: img("photo-1460317442991-0ec209397118"), type: "image", display_order: 1 },
      ],
      roi: { id: "ar", annual_return: 5.9, capital_appreciation: 7.3, rental_yield: 4.1, exit_horizon: "3 years" },
    },
  ];

  const events = [
    {
      id: "ev-forum",
      title: "REIFGO Global Investment Forum 2026",
      date: daysAhead(45),
      location: "Marina Bay Sands, Singapore",
      type: "in_person",
      pass_type: "Investor pass",
      description: "Flagship annual forum connecting investors with elite developers across three continents.",
      created_at: daysAgo(80),
      _count: { registrations: 214 },
    },
    {
      id: "ev-webinar",
      title: "UAE Market Outlook — H2 Webinar",
      date: daysAhead(12),
      location: null,
      type: "virtual",
      pass_type: "Free",
      description: "Live analyst briefing on Dubai and Abu Dhabi residential yields.",
      created_at: daysAgo(30),
      _count: { registrations: 892 },
    },
    {
      id: "ev-roadshow",
      title: "London Developer Roadshow",
      date: daysAhead(90),
      location: "The Shard, London",
      type: "in_person",
      pass_type: "Premium",
      description: "Private viewings and 1:1 sessions with Berkeley Group leadership.",
      created_at: daysAgo(15),
      _count: { registrations: 57 },
    },
  ];

  const users = [
    {
      id: "u1",
      phone: "+971 50 123 4567",
      full_name: "Khalid Al Mansoori",
      email: "khalid.m@example.com",
      nationality: "Emirati",
      country: "UAE",
      city: "Dubai",
      area_of_interest: "Residential",
      tier: "premium_investor",
      is_verified: true,
      created_at: daysAgo(140),
      registered_events: [
        { registered_at: daysAgo(20), event: { id: "ev-forum", title: "REIFGO Global Investment Forum 2026", date: daysAhead(45) } },
      ],
      _count: { leads: 2, saved_properties: 4 },
    },
    {
      id: "u2",
      phone: "+44 7700 900123",
      full_name: "Sarah Whitfield",
      email: "sarah.w@example.com",
      nationality: "British",
      country: "UK",
      city: "London",
      area_of_interest: "Commercial",
      tier: "regular",
      is_verified: true,
      created_at: daysAgo(95),
      registered_events: [
        { registered_at: daysAgo(8), event: { id: "ev-webinar", title: "UAE Market Outlook — H2 Webinar", date: daysAhead(12) } },
      ],
      _count: { leads: 1, saved_properties: 2 },
    },
    {
      id: "u3",
      phone: "+1 917 555 0188",
      full_name: "Daniel Osei",
      email: null,
      nationality: "American",
      country: "USA",
      city: "New York",
      area_of_interest: "Mixed-use",
      tier: "regular",
      is_verified: false,
      created_at: daysAgo(12),
      registered_events: [],
      _count: { leads: 1, saved_properties: 0 },
    },
  ];

  const leads = [
    {
      id: "l1",
      user_id: "u1",
      property_id: "marina-gate",
      lead_type: "express_interest",
      status: "pending",
      created_at: daysAgo(1),
    },
    {
      id: "l2",
      user_id: "u2",
      property_id: "nexus",
      lead_type: "callback_request",
      status: "pending",
      created_at: daysAgo(2),
    },
    {
      id: "l3",
      user_id: "u1",
      property_id: "zenith",
      lead_type: "document_request",
      status: "contacted",
      created_at: daysAgo(6),
    },
    {
      id: "l4",
      user_id: "u3",
      property_id: "aster-park",
      lead_type: "express_interest",
      status: "closed",
      created_at: daysAgo(14),
    },
  ];

  return { developers, properties, events, users, leads };
}
