// Sample dataset for demo mode (no backend configured). Shapes mirror the
// NestJS admin API responses exactly, so the pages don't know the difference.

const daysAgo = (n) => new Date(Date.now() - n * 86400000).toISOString();
const daysAhead = (n) => new Date(Date.now() + n * 86400000).toISOString();
const hoursAgo = (n) => new Date(Date.now() - n * 3600000).toISOString();

const img = (id) => `https://images.unsplash.com/${id}?w=800&q=80`;

export function createDemoData() {
  const developers = [
    {
      id: "solaris",
      name: "SOLARIS DEVELOPMENTS",
      tagline: "Architecture for the next century",
      years_in_market: 22,
      total_projects: 48,
      international_hubs: "Dubai · London · Singapore",
      hero_image_url: img("photo-1486325212027-8081e485255e"),
      is_verified: true,
      is_approved: true,
      created_at: daysAgo(300),
      values: [
        { id: "sv1", icon: "trust", title: "Integrity", description: "Transparent reporting on every project.", display_order: 0 },
        { id: "sv2", icon: "quality", title: "Craftsmanship", description: "Award-winning architectural partners.", display_order: 1 },
      ],
    },
    {
      id: "berkeley",
      name: "HARBOUR GROUP",
      tagline: "London's landmark builder",
      years_in_market: 35,
      total_projects: 120,
      international_hubs: "London · Manchester",
      hero_image_url: img("photo-1464938050520-ef2270bb8ce8"),
      is_verified: true,
      is_approved: true,
      created_at: daysAgo(260),
      values: [
        { id: "bv1", icon: "global", title: "Heritage", description: "Three decades of delivery.", display_order: 0 },
      ],
    },
    {
      id: "meraas",
      name: "VANTAGE HOLDING",
      tagline: "Shaping Dubai's waterfront",
      years_in_market: 17,
      total_projects: 36,
      international_hubs: "Dubai · Abu Dhabi",
      hero_image_url: img("photo-1512453979798-5ea266f8880c"),
      is_verified: true,
      is_approved: false,
      created_at: daysAgo(180),
      values: [],
    },
    {
      id: "emaar",
      name: "MERIDIAN PROPERTIES",
      tagline: "Abu Dhabi's landmark developer",
      years_in_market: 20,
      total_projects: 92,
      international_hubs: "Abu Dhabi · Dubai",
      hero_image_url: img("photo-1518684079-3c830dcef090"),
      is_verified: true,
      is_approved: true,
      created_at: daysAgo(220),
      values: [
        { id: "alv1", icon: "trust", title: "Landmark quality", description: "Yas Island and Saadiyat flagships.", display_order: 0 },
        { id: "alv2", icon: "global", title: "Sustainable design", description: "Estidama Pearl-rated communities.", display_order: 1 },
      ],
    },
    {
      id: "reportage",
      name: "CORNERSTONE PROPERTIES",
      tagline: "Contemporary living, accessible entry",
      years_in_market: 11,
      total_projects: 40,
      international_hubs: "Abu Dhabi · Dubai · Cairo",
      hero_image_url: img("photo-1512917774080-9991f1c4c750"),
      is_verified: true,
      is_approved: true,
      created_at: daysAgo(150),
      values: [
        { id: "rpv1", icon: "quality", title: "Design-led", description: "Modern architecture at competitive pricing.", display_order: 0 },
      ],
    },
    {
      id: "aster",
      name: "ASTER CAPITAL ESTATES",
      tagline: "Boutique developments, institutional returns",
      years_in_market: 9,
      total_projects: 14,
      international_hubs: "New York · Miami",
      hero_image_url: img("photo-1449824913935-59a10b8d2000"),
      is_verified: false,
      is_approved: true,
      created_at: daysAgo(90),
      values: [],
    },
  ];

  const properties = [
    {
      id: "zenith",
      developer_id: "solaris",
      name: "The Zenith Residence",
      location: "Shoreditch, London",
      asset_class: "Multi-family",
      total_area: 87400,
      completion_date: daysAhead(420),
      min_entry_price: 25000,
      sustainability_rating: 4.0,
      overview:
        "The Zenith Residence redefines urban living in the heart of Shoreditch, blending contemporary architecture with community-centred design.",
      status: "active",
      created_at: daysAgo(200),
      media: [
        { id: "zm1", url: img("photo-1486325212027-8081e485255e"), type: "image", display_order: 0 },
        { id: "zm2", url: img("photo-1545324418-cc1a3fa10c00"), type: "image", display_order: 1 },
        { id: "zm3", url: img("photo-1560448204-e02f11c3d0e2"), type: "image", display_order: 2 },
      ],
      roi: { id: "zr", annual_return: 7.8, capital_appreciation: 5.2, rental_yield: 4.6, exit_horizon: "5 years" },
    },
    {
      id: "nexus",
      developer_id: "berkeley",
      name: "Nexus Plaza II",
      location: "London, Commercial District",
      asset_class: "Commercial",
      total_area: 145000,
      completion_date: daysAhead(540),
      min_entry_price: 35000,
      sustainability_rating: 4.0,
      overview: "A landmark commercial development anchoring the district's regeneration masterplan.",
      status: "active",
      created_at: daysAgo(160),
      media: [
        { id: "nm1", url: img("photo-1464938050520-ef2270bb8ce8"), type: "image", display_order: 0 },
        { id: "nm2", url: img("photo-1554435493-93422e8220c8"), type: "image", display_order: 1 },
      ],
      roi: { id: "nr", annual_return: 6.2, capital_appreciation: 4.8, rental_yield: 3.2, exit_horizon: "5–7 years" },
    },
    {
      id: "marina-gate",
      developer_id: "meraas",
      name: "Marina Gate Towers",
      location: "Dubai Marina, UAE",
      asset_class: "Residential",
      total_area: 210000,
      completion_date: daysAhead(720),
      min_entry_price: 50000,
      sustainability_rating: 4.5,
      overview: "Twin waterfront towers with panoramic marina views and hotel-grade amenities.",
      status: "coming_soon",
      created_at: daysAgo(120),
      media: [
        { id: "mm1", url: img("photo-1512453979798-5ea266f8880c"), type: "image", display_order: 0 },
      ],
      roi: { id: "mr", annual_return: 8.4, capital_appreciation: 6.1, rental_yield: 5.5, exit_horizon: "4 years" },
    },
    {
      id: "yas-bay",
      developer_id: "emaar",
      name: "Yas Bay Waterfront Residences",
      location: "Yas Island, Abu Dhabi",
      asset_class: "Residential",
      total_area: 168000,
      completion_date: daysAhead(500),
      min_entry_price: 40000,
      sustainability_rating: 4.5,
      overview: "Waterfront apartments on Yas Bay's entertainment promenade, steps from the arena and marina.",
      status: "active",
      created_at: daysAgo(100),
      media: [
        { id: "ybm1", url: img("photo-1518684079-3c830dcef090"), type: "image", display_order: 0 },
        { id: "ybm2", url: img("photo-1522708323590-d24dbb6b0267"), type: "image", display_order: 1 },
      ],
      roi: { id: "ybr", annual_return: 7.1, capital_appreciation: 5.8, rental_yield: 6.2, exit_horizon: "5 years" },
    },
    {
      id: "saadiyat-grove",
      developer_id: "emaar",
      name: "Saadiyat Grove Villas",
      location: "Saadiyat Island, Abu Dhabi",
      asset_class: "Residential",
      total_area: 96000,
      completion_date: daysAhead(760),
      min_entry_price: 75000,
      sustainability_rating: 5,
      overview: "Limited collection of villas in the Saadiyat cultural district, beside the museums quarter.",
      status: "coming_soon",
      created_at: daysAgo(40),
      media: [
        { id: "sgm1", url: img("photo-1600596542815-ffad4c1539a9"), type: "image", display_order: 0 },
      ],
      roi: { id: "sgr", annual_return: 6.4, capital_appreciation: 7.0, rental_yield: 4.9, exit_horizon: "7 years" },
    },
    {
      id: "rukan-tower",
      developer_id: "reportage",
      name: "Rukan Tower II",
      location: "Dubailand, Dubai",
      asset_class: "Residential",
      total_area: 88000,
      completion_date: daysAhead(300),
      min_entry_price: 18000,
      sustainability_rating: 3.5,
      overview: "Efficient studios and one-beds aimed at the mid-market rental segment in Dubailand.",
      status: "active",
      created_at: daysAgo(75),
      media: [
        { id: "rtm1", url: img("photo-1512917774080-9991f1c4c750"), type: "image", display_order: 0 },
      ],
      roi: { id: "rtr", annual_return: 8.9, capital_appreciation: 4.2, rental_yield: 7.4, exit_horizon: "3 years" },
    },
    {
      id: "aster-park",
      developer_id: "aster",
      name: "Aster Park Lofts",
      location: "Brooklyn, New York",
      asset_class: "Mixed-use",
      total_area: 64000,
      completion_date: daysAgo(60),
      min_entry_price: 20000,
      sustainability_rating: 3.5,
      overview: "Converted industrial lofts with retail podium in a fast-appreciating neighbourhood.",
      status: "sold_out",
      created_at: daysAgo(340),
      media: [
        { id: "am1", url: img("photo-1449824913935-59a10b8d2000"), type: "image", display_order: 0 },
        { id: "am2", url: img("photo-1460317442991-0ec209397118"), type: "image", display_order: 1 },
      ],
      roi: { id: "ar", annual_return: 5.9, capital_appreciation: 7.3, rental_yield: 4.1, exit_horizon: "3 years" },
    },
  ];

  const events = [
    {
      id: "ev-forum",
      title: "REIFGO Global Investment Forum 2026",
      date: daysAhead(45),
      location: "Marina Bay Sands, Singapore",
      type: "in_person",
      pass_type: "Investor pass",
      description: "Flagship annual forum connecting investors with elite developers across three continents.",
      created_at: daysAgo(80),
      _count: { registrations: 214 },
    },
    {
      id: "ev-webinar",
      title: "UAE Market Outlook — H2 Webinar",
      date: daysAhead(12),
      location: null,
      type: "virtual",
      pass_type: "Free",
      description: "Live analyst briefing on Dubai and Abu Dhabi residential yields.",
      created_at: daysAgo(30),
      _count: { registrations: 892 },
    },
    {
      id: "ev-roadshow",
      title: "London Developer Roadshow",
      date: daysAhead(90),
      location: "The Shard, London",
      type: "in_person",
      pass_type: "Premium",
      description: "Private viewings and 1:1 sessions with Harbour Group leadership.",
      created_at: daysAgo(15),
      _count: { registrations: 57 },
    },
  ];

  const users = [
    {
      id: "u1",
      phone: "+971 50 123 4567",
      full_name: "Khalid Al Mansoori",
      email: "khalid.m@example.com",
      nationality: "Emirati",
      country: "UAE",
      city: "Dubai",
      area_of_interest: "Residential",
      tier: "premium_investor",
      is_verified: true,
      created_at: daysAgo(140),
      registered_events: [
        { registered_at: daysAgo(20), event: { id: "ev-forum", title: "REIFGO Global Investment Forum 2026", date: daysAhead(45) } },
      ],
      _count: { leads: 2, saved_properties: 4 },
    },
    {
      id: "u2",
      phone: "+44 7700 900123",
      full_name: "Sarah Whitfield",
      email: "sarah.w@example.com",
      nationality: "British",
      country: "UK",
      city: "London",
      area_of_interest: "Commercial",
      tier: "regular",
      is_verified: true,
      created_at: daysAgo(95),
      registered_events: [
        { registered_at: daysAgo(8), event: { id: "ev-webinar", title: "UAE Market Outlook — H2 Webinar", date: daysAhead(12) } },
      ],
      _count: { leads: 1, saved_properties: 2 },
    },
    {
      id: "u3",
      phone: "+1 917 555 0188",
      full_name: "Daniel Osei",
      email: null,
      nationality: "American",
      country: "USA",
      city: "New York",
      area_of_interest: "Mixed-use",
      tier: "regular",
      is_verified: false,
      created_at: daysAgo(12),
      registered_events: [],
      _count: { leads: 1, saved_properties: 0 },
    },
    {
      id: "u4",
      phone: "+971 55 771 4090",
      full_name: "Aisha Noor",
      email: "aisha.noor@example.com",
      nationality: "Emirati",
      country: "UAE",
      city: "Abu Dhabi",
      area_of_interest: "Residential",
      tier: "premium_investor",
      is_verified: true,
      created_at: daysAgo(60),
      registered_events: [],
      _count: { leads: 2, saved_properties: 3 },
    },
    {
      id: "u5",
      phone: "+65 8123 4455",
      full_name: "Marcus Chen",
      email: "marcus.chen@example.com",
      nationality: "Singaporean",
      country: "Singapore",
      city: "Singapore",
      area_of_interest: "Residential",
      tier: "regular",
      is_verified: true,
      created_at: daysAgo(45),
      registered_events: [],
      _count: { leads: 2, saved_properties: 1 },
    },
  ];

  // Brokers work under a developer. Each developer's team assigns leads to
  // its brokers; a broker only sees the leads assigned to them.
  const brokers = [
    { id: "bk-omar", developer_id: "emaar", name: "Omar Al Farsi", email: "omar@meridian.example", phone: "+971 50 200 1188" },
    { id: "bk-fatima", developer_id: "emaar", name: "Fatima Zahra", email: "fatima@meridian.example", phone: "+971 50 200 3300" },
    { id: "bk-yusuf", developer_id: "reportage", name: "Yusuf Rahman", email: "yusuf@cornerstone.example", phone: "+971 50 400 7722" },
  ];

  // Lead activity entries are the audit trail: creation, assignment, status
  // changes and free-text notes — reverse-chronological in the UI.
  let aseq = 0;
  const act = (at, actor, type, note) => ({ id: `act-${++aseq}`, at, actor, type, note });

  const leads = [
    // Fresh, unassigned — the developer still needs to route it.
    {
      id: "l1",
      user_id: "u1",
      property_id: "yas-bay",
      lead_type: "express_interest",
      status: "new",
      assigned_broker_id: null,
      created_at: hoursAgo(3),
      assigned_at: null,
      first_response_at: null,
      closed_at: null,
      activity: [act(hoursAgo(3), "Khalid Al Mansoori", "creation", "Lead submitted via the app")],
    },
    // Assigned, still inside the 24h response window.
    {
      id: "l2",
      user_id: "u2",
      property_id: "yas-bay",
      lead_type: "callback_request",
      status: "assigned",
      assigned_broker_id: "bk-omar",
      created_at: hoursAgo(8),
      assigned_at: hoursAgo(6),
      first_response_at: null,
      closed_at: null,
      activity: [
        act(hoursAgo(6), "MERIDIAN PROPERTIES", "assignment", "Assigned to Omar Al Farsi"),
        act(hoursAgo(8), "Sarah Whitfield", "creation", "Lead submitted via the app"),
      ],
    },
    // Assigned 30h ago, no response yet — escalated to the developer.
    {
      id: "l3",
      user_id: "u3",
      property_id: "saadiyat-grove",
      lead_type: "document_request",
      status: "assigned",
      assigned_broker_id: "bk-fatima",
      created_at: hoursAgo(32),
      assigned_at: hoursAgo(30),
      first_response_at: null,
      closed_at: null,
      activity: [
        act(hoursAgo(30), "MERIDIAN PROPERTIES", "assignment", "Assigned to Fatima Zahra"),
        act(hoursAgo(32), "Daniel Osei", "creation", "Lead submitted via the app"),
      ],
    },
    // Assigned 54h ago, still no response — escalated all the way to REIFGO.
    {
      id: "l4",
      user_id: "u4",
      property_id: "yas-bay",
      lead_type: "express_interest",
      status: "assigned",
      assigned_broker_id: "bk-omar",
      created_at: hoursAgo(56),
      assigned_at: hoursAgo(54),
      first_response_at: null,
      closed_at: null,
      activity: [
        act(hoursAgo(54), "MERIDIAN PROPERTIES", "assignment", "Assigned to Omar Al Farsi"),
        act(hoursAgo(56), "Aisha Noor", "creation", "Lead submitted via the app"),
      ],
    },
    // Responded in ~4h — healthy.
    {
      id: "l5",
      user_id: "u5",
      property_id: "saadiyat-grove",
      lead_type: "callback_request",
      status: "contacted",
      assigned_broker_id: "bk-fatima",
      created_at: hoursAgo(22),
      assigned_at: hoursAgo(20),
      first_response_at: hoursAgo(16),
      closed_at: null,
      activity: [
        act(hoursAgo(16), "Fatima Zahra", "note", "Called the investor, sent the Saadiyat brochure. Following up Thursday."),
        act(hoursAgo(16), "Fatima Zahra", "status", "Status → Contacted"),
        act(hoursAgo(20), "MERIDIAN PROPERTIES", "assignment", "Assigned to Fatima Zahra"),
        act(hoursAgo(22), "Marcus Chen", "creation", "Lead submitted via the app"),
      ],
    },
    // Qualified — genuine intent confirmed.
    {
      id: "l6",
      user_id: "u1",
      property_id: "yas-bay",
      lead_type: "express_interest",
      status: "qualified",
      assigned_broker_id: "bk-omar",
      created_at: daysAgo(5),
      assigned_at: hoursAgo(118),
      first_response_at: hoursAgo(115),
      closed_at: null,
      activity: [
        act(hoursAgo(70), "Omar Al Farsi", "status", "Status → Qualified"),
        act(hoursAgo(72), "Omar Al Farsi", "note", "Budget confirmed at $60k entry, wants a 2-bed. Strong fit."),
        act(hoursAgo(115), "Omar Al Farsi", "status", "Status → Contacted"),
        act(hoursAgo(118), "MERIDIAN PROPERTIES", "assignment", "Assigned to Omar Al Farsi"),
        act(daysAgo(5), "Khalid Al Mansoori", "creation", "Lead submitted via the app"),
      ],
    },
    // Closed — won.
    {
      id: "l7",
      user_id: "u2",
      property_id: "saadiyat-grove",
      lead_type: "document_request",
      status: "closed_won",
      assigned_broker_id: "bk-fatima",
      created_at: daysAgo(12),
      assigned_at: hoursAgo(286),
      first_response_at: hoursAgo(284),
      closed_at: daysAgo(2),
      activity: [
        act(daysAgo(2), "Fatima Zahra", "status", "Status → Closed (won)"),
        act(daysAgo(2), "Fatima Zahra", "note", "Reservation signed on a Saadiyat villa. 🎉"),
        act(hoursAgo(284), "Fatima Zahra", "status", "Status → Contacted"),
        act(hoursAgo(286), "MERIDIAN PROPERTIES", "assignment", "Assigned to Fatima Zahra"),
        act(daysAgo(12), "Sarah Whitfield", "creation", "Lead submitted via the app"),
      ],
    },
    // Closed — lost.
    {
      id: "l8",
      user_id: "u3",
      property_id: "yas-bay",
      lead_type: "callback_request",
      status: "closed_lost",
      assigned_broker_id: "bk-omar",
      created_at: daysAgo(20),
      assigned_at: hoursAgo(478),
      first_response_at: hoursAgo(473),
      closed_at: daysAgo(8),
      activity: [
        act(daysAgo(8), "Omar Al Farsi", "status", "Status → Closed (lost)"),
        act(daysAgo(8), "Omar Al Farsi", "note", "Investor went with another development. Not price-sensitive — timing."),
        act(hoursAgo(473), "Omar Al Farsi", "status", "Status → Contacted"),
        act(hoursAgo(478), "MERIDIAN PROPERTIES", "assignment", "Assigned to Omar Al Farsi"),
        act(daysAgo(20), "Daniel Osei", "creation", "Lead submitted via the app"),
      ],
    },
    // Cornerstone lead, assigned to Yusuf — gives the second company real data.
    {
      id: "l9",
      user_id: "u5",
      property_id: "rukan-tower",
      lead_type: "express_interest",
      status: "assigned",
      assigned_broker_id: "bk-yusuf",
      created_at: hoursAgo(11),
      assigned_at: hoursAgo(9),
      first_response_at: null,
      closed_at: null,
      activity: [
        act(hoursAgo(9), "CORNERSTONE PROPERTIES", "assignment", "Assigned to Yusuf Rahman"),
        act(hoursAgo(11), "Marcus Chen", "creation", "Lead submitted via the app"),
      ],
    },
    // A lead on a developer that has no broker accounts yet — shows the
    // admin's cross-portfolio view and an unrouted lead.
    {
      id: "l10",
      user_id: "u4",
      property_id: "nexus",
      lead_type: "express_interest",
      status: "new",
      assigned_broker_id: null,
      created_at: daysAgo(1),
      assigned_at: null,
      first_response_at: null,
      closed_at: null,
      activity: [act(daysAgo(1), "Aisha Noor", "creation", "Lead submitted via the app")],
    },
  ];

  // CMS-authored articles. The four "published + website" ones mirror the
  // cards hardcoded on the landing page's Insights section, so the site
  // looks identical until someone edits them in the CMS.
  const insights = [
    {
      id: "in-trends",
      title: "Global market trends and analysis",
      category: "Market Report",
      excerpt: "Quarterly deep-dives into regional growth and volatility.",
      body: "Full report body goes here — regional absorption, yield movement and capital flows across the REIFGO markets.",
      cover_url: "",
      author_name: "REIFGO Research",
      author_developer_id: null,
      channels: { app: true, website: true },
      published: true,
      created_at: daysAgo(9),
    },
    {
      id: "in-interviews",
      title: "Developer interviews and profiles",
      category: "Interview",
      excerpt: "Conversations with the minds behind iconic projects.",
      body: "",
      cover_url: "",
      author_name: "REIFGO Research",
      author_developer_id: null,
      channels: { app: true, website: true },
      published: true,
      created_at: daysAgo(16),
    },
    {
      id: "in-guides",
      title: "Investment guides and best practices",
      category: "Guide",
      excerpt: "Essential resources for cross-border asset management.",
      body: "",
      cover_url: "",
      author_name: "REIFGO Research",
      author_developer_id: null,
      channels: { app: true, website: true },
      published: true,
      created_at: daysAgo(23),
    },
    {
      id: "in-updates",
      title: "Project updates and announcements",
      category: "Announcement",
      excerpt: "Breaking news from our developer network globally.",
      body: "",
      cover_url: "",
      author_name: "REIFGO Research",
      author_developer_id: null,
      channels: { app: true, website: true },
      published: true,
      created_at: daysAgo(30),
    },
    {
      id: "in-emaar-q3",
      title: "Yas Island Q3 absorption update",
      category: "Market Report",
      excerpt: "Waterfront units are moving 22% faster than the Abu Dhabi average.",
      body: "Draft — numbers pending final verification from the sales desk.",
      cover_url: "",
      author_name: "MERIDIAN PROPERTIES",
      author_developer_id: "emaar",
      channels: { app: true, website: false },
      published: false,
      created_at: daysAgo(2),
    },
  ];

  // Where each record is shown. Mirrors the visibility flags the real
  // schema will need (channels columns on Property/Event/Insight).
  for (const p of properties) p.channels = { app: true, website: true };
  properties.find((p) => p.id === "rukan-tower").channels = { app: true, website: false };
  for (const e of events) e.channels = { app: true, website: true };

  // App leads carry source "app"; website form submissions get "website".
  for (const l of leads) l.source = "app";

  return { developers, properties, events, users, brokers, leads, insights };
}
