// Where an investor lives, as the app's profile form offers it, and the
// REIFGO region each falls under. Generated from REIFGO/backend/src/residence.ts
// (the app has the same list in REIFGO/constants/residence.ts); change all three together.
export const RESIDENCE = [
  ["United Arab Emirates", "UAE"],
  ["Saudi Arabia", "Saudi Arabia"],
  ["Qatar", "Qatar"],
  ["Bahrain", "Bahrain"],
  ["Kuwait", "Kuwait"],
  ["Oman", "Oman"],
  ["Egypt", "Egypt"],
  ["Turkey", "Turkey"],
  ["United Kingdom", "United Kingdom"],
  ["Austria", "Europe"],
  ["Belgium", "Europe"],
  ["Cyprus", "Europe"],
  ["Czech Republic", "Europe"],
  ["Denmark", "Europe"],
  ["Finland", "Europe"],
  ["France", "Europe"],
  ["Georgia", "Europe"],
  ["Germany", "Europe"],
  ["Greece", "Europe"],
  ["Hungary", "Europe"],
  ["Ireland", "Europe"],
  ["Italy", "Europe"],
  ["Malta", "Europe"],
  ["Montenegro", "Europe"],
  ["Netherlands", "Europe"],
  ["Norway", "Europe"],
  ["Poland", "Europe"],
  ["Portugal", "Europe"],
  ["Romania", "Europe"],
  ["Russia", "Europe"],
  ["Serbia", "Europe"],
  ["Spain", "Europe"],
  ["Sweden", "Europe"],
  ["Switzerland", "Europe"],
  ["Ukraine", "Europe"],
  ["Canada", "North America"],
  ["Mexico", "North America"],
  ["United States", "North America"],
  ["Afghanistan", "Asia"],
  ["Azerbaijan", "Asia"],
  ["Bangladesh", "Asia"],
  ["China", "Asia"],
  ["Hong Kong", "Asia"],
  ["India", "Asia"],
  ["Indonesia", "Asia"],
  ["Iran", "Asia"],
  ["Iraq", "Asia"],
  ["Japan", "Asia"],
  ["Jordan", "Asia"],
  ["Kazakhstan", "Asia"],
  ["Lebanon", "Asia"],
  ["Malaysia", "Asia"],
  ["Maldives", "Asia"],
  ["Nepal", "Asia"],
  ["Pakistan", "Asia"],
  ["Palestine", "Asia"],
  ["Philippines", "Asia"],
  ["Singapore", "Asia"],
  ["South Korea", "Asia"],
  ["Sri Lanka", "Asia"],
  ["Syria", "Asia"],
  ["Thailand", "Asia"],
  ["Uzbekistan", "Asia"],
  ["Vietnam", "Asia"],
  ["Yemen", "Asia"],
  ["Algeria", "Africa"],
  ["Ethiopia", "Africa"],
  ["Ghana", "Africa"],
  ["Kenya", "Africa"],
  ["Libya", "Africa"],
  ["Mauritius", "Africa"],
  ["Morocco", "Africa"],
  ["Nigeria", "Africa"],
  ["Seychelles", "Africa"],
  ["South Africa", "Africa"],
  ["Sudan", "Africa"],
  ["Tunisia", "Africa"],
  ["Argentina", null],
  ["Australia", null],
  ["Brazil", null],
  ["Colombia", null],
  ["New Zealand", null],
  ["Other", null],
];

// For pickers: the Gulf and REIFGO's home markets first, then A–Z, then "Other".
export const RESIDENCE_NAMES = [
  ...RESIDENCE.slice(0, 9).map(([n]) => n),
  ...RESIDENCE.slice(9).map(([n]) => n).filter((n) => n !== "Other").sort((a, b) => a.localeCompare(b)),
  "Other",
];
